### ISSUE TITLE
After generating grunt fails : uncaught reference error

### ISSUE THREAD

**Issue by timothyjlaurent** [wlepinski/generator-meanstack#9] opened 2013-11-22 06:30 UTC
WARN [watcher]: Pattern "/Users/MyMBP/Development/yo-mean/test/mock/*_/_.js" does not match any file.
INFO [Chrome 31.0 (Mac)]: Connected on socket id 9k_VbFZPuhWNiJsnegMd
Chrome 31.0 (Mac) ERROR
    Uncaught ReferenceError: angular is not defined
    at /Users/MyMBP/Development/yo-mean/app/scripts/app.js:3
Chrome 31.0 (Mac): Executed 0 of 0 ERROR (0.922 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

**Comment by wlepinski** [comment] 2013-11-27 00:28
@timothyjlaurent I was not able to reproduce this issue here. Could you provide detailed steps? Thanks.

**Comment by timothyjlaurent** [comment] 2013-12-05 00:07
Ok so I tried again , reinstalling npm and yo but was getting the same error.  I then did a global install of bower 'sudo npm install bower' and the issues went away.

I am stoked!!

**Comment by wlepinski** [comment] 2013-12-05 13:41
That's good. Let me know if you have other issues. Closing.

**Closed as completed by wlepinski** 2013-12-05 13:41 UTC
